version: "3.8"

networks:
  minhas_horas:
    driver: bridge

services:
  # custom image
  mytime:
    build:
      args:
        user: wallace
        uid: 1000
      dockerfile: Dockerfile
    image: wallacemartinss
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    restart: unless-stopped
    depends_on:
      - redis
      - queue
      - mysql
      - mailhog
    networks:
      - minhas_horas
  
  #nginx
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - minhas_horas

  # db
  mysql:
    image: mysql:8.0.27
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      LANG: C.UTF-8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - minhas_horas

   # redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - minhas_horas

  # MailHog
  mailhog:
    image: mailhog/mailhog:latest
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  # queue
  queue:
    build:
      args:
        user: wallace
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    restart: always
    command: "php artisan queue:work"
    volumes:
      - ./:/var/www
    depends_on:
      - redis
    networks:
      - minhas_horas